on:
  push:
    branches:
      - main
      - master
  pull_request:

name: Continuous integration

jobs:
  test:
    name: Check, Clippy, Format, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install musl-tools
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: Swatinem/rust-cache@v1
        with: { sharedKey: ci }
      - uses: jorelali/setup-elm@v2
        with:
          elm-version: 0.19.1
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - run: rustup component add clippy
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - run: rustup component add rustfmt
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target x86_64-unknown-linux-musl
